# Site settings
title: "Bi Han & Ja Yeon"
email: "naturekimj@gmail.com"
description: | 
  서로가 있기에 눈뜨는 아침이 행복했습니다.
  이제 그 행복을 곁에서 함께하려합니다.
  저희의 시작하는 모습을 여러분과 함께 하고 싶습니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "herenowalways@github.io" # the base hostname & protocol for your site

# User setting
owner: "Jayeon & Bihan"
email: "naturekimj@gmail.com"
facebook_username: blacksianj
twitter_username:
github_username: herenowalways
address: "헤이스가든"
location: Seoul
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key: AIzaSyAtKAlVSqS4XxEVNOfM1lbDVoEKiKvUxPw

# Build settings
markdown: kramdown

#disqus
disqus_id: herenowalways
